version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/tasks_development
      - RAILS_MASTER_KEY=ae440dac1d45e6769056e81121b3afac # I know. This has not been hidden for simplicity
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules

    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=tasks_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate:
    build: .
    command: rails db:migrate
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/tasks_development
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
