default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tasks_development
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "samuelecastiglia" } %>
  password: 123456
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

test:
  <<: *default
  database: tasks_test
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "samuelecastiglia" } %>
  password: 123456
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

production:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cache:
    url: <%= ENV['CACHE_DATABASE_URL'] || ENV['DATABASE_URL']&.sub(/\/[^\/]*$/, '/tasks_production_cache') %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    migrations_paths: db/cache_migrate
  queue:
    url: <%= ENV['QUEUE_DATABASE_URL'] || ENV['DATABASE_URL']&.sub(/\/[^\/]*$/, '/tasks_production_queue') %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    migrations_paths: db/queue_migrate
  cable:
    url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL']&.sub(/\/[^\/]*$/, '/tasks_production_cable') %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    migrations_paths: db/cable_migrate
